"""
Django settings for pi_dep project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^ef1u080)8y)q3jdrawdw05(2cc_$sidh$r&5bv(xk3)+m(u#!"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'chaimatlili62@gmail.com'  # celui qui envoie
EMAIL_HOST_PASSWORD = 'iypg brnf qkpe htsv'  # mot de passe d’application
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "patient",
    "radiologue",
    "account",

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pi_dep.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ['template'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pi_dep.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

import os

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Ajouté pour servir les fichiers statiques manuellement placés à la racine


# Recommandé pour que collectstatic fonctionne proprement
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'static', 'media')  # Répertoire pour les fichiers uploadés

# Répertoires des images pour les différentes étapes du pipeline
STAGE_IMAGES_DIR = os.path.join(MEDIA_ROOT, 'stage')  # Images pour VGG
MALIGNANT_IMAGES_DIR = os.path.join(MEDIA_ROOT, 'malignant') 
LUNA_IMAGES_DIR = os.path.join(MEDIA_ROOT, 'luna')

 # Images pour YOLO
# TEMPLATES (corrigé pour le chargement HTML depuis la racine)
TEMPLATES[0]['DIRS'] = [BASE_DIR / "templates", BASE_DIR]
AUTH_USER_MODEL = 'account.CustomUser'
LOGIN_REDIRECT_URL = 'dashboard'

# Allow embedding Power BI resources
X_FRAME_OPTIONS = 'ALLOWALL'  # Allows all content to be embedded

# Alternatively, to allow specific domains
X_FRAME_OPTIONS = 'SAMEORIGIN'  # Allows iframe content from the same origin

# If using Django 3.0+, ensure CSP (Content Security Policy) is not blocking external requests
CSP_FRAME_SRC = ["'self'", "https://app.powerbi.com"]
CSP_SCRIPT_SRC = ("https://app.powerbi.com",)
CSP_DEFAULT_SRC = ["'self'"]
SECURE_CROSS_ORIGIN_OPENER_POLICY = None


SECURE_CROSS_ORIGIN_OPENER_POLICY = None


ALLOWED_HOSTS = []

# Allow embedding Power BI resources
X_FRAME_OPTIONS = 'ALLOWALL'  # Allows all content to be embedded

# Alternatively, to allow specific domains
X_FRAME_OPTIONS = 'SAMEORIGIN'  # Allows iframe content from the same origin

# If using Django 3.0+, ensure CSP (Content Security Policy) is not blocking external requests
CSP_FRAME_SRC = ["'self'", "https://app.powerbi.com"]
CSP_SCRIPT_SRC = ("https://app.powerbi.com",)
CSP_DEFAULT_SRC = ["'self'"]

