# Generated by Django 5.2 on 2025-05-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radiologue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="radiologue",
            name="image",
            field=models.FileField(
                default="default_image.jpg", upload_to="static/media/luna/"
            ),
        ),
    ]
