# Generated by Django 5.2 on 2025-05-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radiologue", "0002_radiologue_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="radiologue",
            name="image",
            field=models.FileField(
                default="default_image.jpg", upload_to="static/media/luna"
            ),
        ),
    ]
