# Generated by Django 5.2 on 2025-05-04 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "trailer_url",
                    models.URLField(
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="Trailer URL",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Action", "Action"),
                            ("Comedy", "Comedy"),
                            ("Drama", "Drama"),
                            ("Horror", "Horror"),
                            ("Sci-Fi", "Sci-Fi"),
                            ("Romance", "Romance"),
                            ("Animation", "Animation"),
                            ("Thriller", "Thriller"),
                            ("Documentary", "Documentary"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "release_year",
                    models.PositiveIntegerField(
                        help_text="Enter a valid year.",
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2025),
                        ],
                    ),
                ),
                (
                    "poster_image",
                    models.ImageField(
                        upload_to="static/img",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
