# Generated by Django 5.2 on 2025-05-10 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="poster_image",
            field=models.ImageField(
                upload_to="img",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
    ]
